# trigger:
# - master

# pool:
#   vmImage: 'windows-latest'

# variables:
#   solution: '**/*.sln'
#   buildPlatform: 'Any CPU'
#   buildConfiguration: 'Release'

# steps:
# - task: NuGetToolInstaller@1

# - task: NuGetCommand@2
#   inputs:
#     restoreSolution: '$(solution)'

# - task: VSBuild@1
#   inputs:
#     solution: '$(solution)'
#     msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)\WebApp.zip"'
#     platform: '$(buildPlatform)'
#     configuration: '$(buildConfiguration)'

# - task: PublishBuildArtifacts@1
#   inputs:
#     PathtoPublish: '$(build.artifactStagingDirectory)'
#     ArtifactName: 'drop'
#     publishLocation: 'Container'
    
# - task: AzureRmWebAppDeployment@4
#   inputs:
#     ConnectionType: 'AzureRM'
#     azureSubscription: 'Azure subscription 1 (588553dd-38a0-4206-a265-4990179bab5b)'
#     appType: 'webApp'
#     WebAppName: 'tfq-delta-care-api-aspnet-uat-app'
#     package: '$(build.artifactStagingDirectory)/WebApp.zip'